name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: 22
    - run: npm ci
    - run: npm run build
    - run: npm run dist
    - run: npm run test


