name: Deploy to GH Pages

on:
  push:
    branches:
      - master

permissions:
  pages: write
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: 22
    - run: npm ci
    - run: npm run build
    - run: npm run dist
    - run: mv dist docs
    - uses: actions/configure-pages@v5
    - uses: actions/upload-pages-artifact@v3
      with:
        path: docs
    - uses: actions/deploy-pages@v4

